apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: github-actions
          image: docker.io/deb0pratim/github-action
          imagePullPolicy: Always
          ports:
            - containerPort: 8000