name: demo-pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build custom container image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setting up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install
      - run: npm test


#  deployment:
#    needs: [build]
#    name: Deploy helm-charts to K8s
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v2

