#name: CI/CD-pipeline
#on:
#  push:
#    branches:
#      - master
#jobs:
#  build:
#    name: Build and Push container image to DockerHub
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v2
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          file: ./Dockerfile
#          push: true
#          tags: deb0pratim/github-action:${{ github.sha }}
#
#
#  deployment:
#    needs: [ build ]
#    name: Deploy into Kubernetes cluster
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v2
#
#      - name: Import kube-config into pipeline
#        uses: Azure/k8s-set-context@v1
#        with:
#          kubeconfig: ${{ secrets.KUBE_CONFIG }}
#
#      - name: HelmChart deployment
#        uses: Azure/k8s-deploy@v1
#        with:
#          namespace: 'github-actions'
#          images: 'docker.io/deb0pratim/github-action:${{ github.sha }}'
#          manifests: |
#            ./k8s_manifests/deployment.yaml
#            ./k8s_manifests/loadbalancer.yaml
#
