name: CI/CD-pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Push container image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set docker-image tag
        run: |
          IMAGE=deb0pratim/github-action:${{ github.sha }}
          echo "DOCKER_IMAGE=$IMAGE" >> $GITHUB_ENV
          echo $IMAGE >> image.txt

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Export digest to file
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Upload image.txt
        uses: actions/upload-artifact@v1
        with:
          name: image-tag
          path: image.txt

  deployment:
    needs: [ build ]
    name: Deploy into Kubernetes cluster
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download image.txt
        uses: actions/download-artifact@v1
        with:
          name: image-tag

      - name: Copy image to env-variable
        run: |
          IMAGE=`cat image-tag/image.txt`
          echo "DOCKER_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Import kube-config into pipeline
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: HelmChart deployment
        uses: Azure/k8s-deploy@v1
        with:
          namespace: github-actions
          images: ${{ env.DOCKER_IMAGE }}
          manifests: |
            ./k8s_manifests/deployment.yaml
            ./k8s_manifests/loadbalancer.yaml

