name: CI/CD-pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Push container image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: deb0pratim/github-action:${{ github.sha }}

      - name: Export digest to file
        run: echo ${{ steps.docker_build.outputs.digest }} > digest.txt

      - name: Upload digest.txt
        uses: actions/upload-artifact@v1
        with:
          name: docker-digest
          path: digest.txt

  deployment:
    needs: [ build ]
    name: Deploy into Kubernetes cluster
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: docker-digest

      - name: Import kube-config into pipeline
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Copy digest to env-variable
        run: |
          docker_digest=`cat docker-digest/digest.txt`
          echo "DOCKER_DIGEST=$docker_digest" >> $GITHUB_ENV

      - name: HelmChart deployment
        uses: Azure/k8s-deploy@v1
        with:
          namespace: github-actions
          images: 'docker.io/deb0pratim/github-action@${{ env.DOCKER_DIGEST }}'
          manifests: |
            ./k8s_manifests/deployment.yaml
            ./k8s_manifests/loadbalancer.yaml

