name: Testing-pipeline
on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: skx/github-action-tester@master
        with:
          script: .github/test-cases.sh